//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClientTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIResponse
    {
        public int Reponse_Id { get; set; }
        public Nullable<System.Guid> Submission_Id { get; set; }
        public Nullable<int> Code { get; set; }
        public string Message { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Is_Return_Transmitted { get; set; }
        public Nullable<System.DateTime> Created_Time_Stamp { get; set; }
        public Nullable<System.DateTime> Updated_Time_Stamp { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    }
}
