//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClientTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuccessStatu
    {
        public int Success_Status_Id { get; set; }
        public string Sequence { get; set; }
        public Nullable<System.Guid> Record_Id { get; set; }
        public Nullable<int> Response_Id { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<System.DateTime> Created_Time_Stamp { get; set; }
        public Nullable<System.DateTime> Updated_Time_Stamp { get; set; }
    }
}
