//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClientTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordError
    {
        public long Record_Error_Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public Nullable<int> Error_Status_Id { get; set; }
    }
}
